if (COMP_NAME STREQUAL mpi-serial)
  string(APPEND CFLAGS " -std=gnu89")
  string(APPEND CXXFLAGS " -std=c++17")
else()
  string(APPEND CFLAGS " -std=gnu99")
  string(APPEND CXXFLAGS " -std=c++17")
endif()
string(APPEND CPPDEFS " -DFORTRANUNDERSCORE -DNO_R16 -DCPRGNU")
set(CXX_LINKER "FORTRAN")
set(FC_AUTO_R8 "-fdefault-real-8 -fdefault-double-8")
string(APPEND FFLAGS " -fconvert=big-endian -ffree-line-length-none -ffixed-line-length-none")
set(FFLAGS_NOOPT "-O0")
set(FIXEDFLAGS "-ffixed-form")
set(FREEFLAGS "-ffree-form")
set(HAS_F2008_CONTIGUOUS "FALSE")
if (compile_threaded)
  string(APPEND CFLAGS " -fopenmp")
  string(APPEND CXXFLAGS " -fopenmp")
  string(APPEND FFLAGS " -fopenmp")
  string(APPEND LDFLAGS " -fopenmp")
endif()
set(MPICC "mpicc")
set(MPICXX "mpicxx")
set(MPIFC "mpif90")
set(SCC "gcc")
set(SCXX "g++")
set(SFC "gfortran")
set(SUPPORTS_CXX "TRUE")

message("C compiler version is ${CMAKE_C_COMPILER_VERSION}")
message("Fortran compiler version is ${CMAKE_Fortran_COMPILER_VERSION}")
if (CMAKE_Fortran_COMPILER_VERSION VERSION_GREATER_EQUAL 10)
  string(APPEND FFLAGS " -fallow-argument-mismatch  -fallow-invalid-boz ")
  if (DEBUG)
    string(APPEND CFLAGS " -g -Wall -O0 -g -fbacktrace -ffpe-trap=invalid,zero,overflow -fcheck=bounds")
    string(APPEND CXXFLAGS " -g -Wall -O0 -g -fbacktrace -ffpe-trap=invalid,zero,overflow -fcheck=bounds")
    string(APPEND FFLAGS " -g -Wall -O0 -g -fbacktrace -ffpe-trap=zero,overflow -fcheck=bounds")
  endif()
else()
  if (DEBUG)
    string(APPEND CFLAGS " -g -Wall -Og -fbacktrace -ffpe-trap=invalid,zero,overflow -fcheck=bounds")
    string(APPEND CXXFLAGS " -g -Wall -Og -fbacktrace -ffpe-trap=invalid,zero,overflow -fcheck=bounds")
    string(APPEND FFLAGS " -g -Wall -Og -fbacktrace -ffpe-trap=zero,overflow -fcheck=bounds")
  endif()
endif()
if (NOT DEBUG)
  string(APPEND CFLAGS " -O2 -ffp-contract=off")
  string(APPEND CXXFLAGS " -O2 -ffp-contract=off")
  string(APPEND FFLAGS " -O2 -ffp-contract=off")
endif()