set(CONFIG_ARGS "--host=cray")
string(APPEND CFLAGS " -qopt-report -march=core-avx2 -no-fma")
string(APPEND FFLAGS " -qopt-report -march=core-avx2 -no-fma")
if (COMP_NAME STREQUAL gptl)
  string(APPEND CPPDEFS " -DHAVE_SLASHPROC")
endif()
if (COMP_NAME STREQUAL mpi-serial)
  string(APPEND CFLAGS " -std=c89 ")
endif()	
set(SCC icx)
set(SFC ifort)
