if (NOT DEBUG)
  string(APPEND CFLAGS " -O -tp=skylake -Mnofma")
endif()
if (NOT DEBUG)
  string(APPEND FFLAGS " -O -tp=skylake -Mnofma")
endif()
string(APPEND FFLAGS " -I$(EXEROOT)/ocn/obj/FMS")
if (NOT DEBUG)
  string(APPEND LDFLAGS " -O -tp=skylake -Mnofma")
endif()
string(APPEND SLIBS " -llapack -lblas")
if (MPILIB STREQUAL mpi-serial)
  string(APPEND SLIBS " -ldl")
endif()
string(APPEND SLIBS " -L${NETCDF_PATH}/lib -lnetcdf -lnetcdff")
message("GPU_TYPE is ${GPU_TYPE} GPU_OFFLOAD is ${GPU_OFFLOAD}")
if (GPU_TYPE STREQUAL v100 AND GPU_OFFLOAD STREQUAL OpenACC)
   string(APPEND FFLAGS  " -acc -gpu=cc70,lineinfo,nofma -Minfo=accel ")
   string(APPEND LDFLAGS " -acc -gpu=cc70,lineinfo,nofma -Minfo=accel ")
endif()