if (COMP_NAME STREQUAL mpi-serial)
   string(APPEND CFLAGS " -std=c89 ")
endif()
if (NOT DEBUG)
  string(APPEND FFLAGS " -tp=zen3")
endif()
message("GPU_TYPE is ${GPU_TYPE}")
message("OPENACC_GPU_OFFLOAD is ${OPENACC_GPU_OFFLOAD}")
message("OPENMP_GPU_OFFLOAD is ${OPENMP_GPU_OFFLOAD}")