if (COMP_NAME STREQUAL mpi-serial)
   string(APPEND CFLAGS " -std=c89 ")
endif()
if (NOT DEBUG)
  string(APPEND FFLAGS " -tp=zen3")
endif()
message("GPU_TYPE is ${GPU_TYPE} GPU_OFFLOAD is ${GPU_OFFLOAD}")
