string(APPEND CPPDEFS " -DHAVE_IEEE_ARITHMETIC")
if (NOT DEBUG)
  if (GPU_TYPE STREQUAL none) # AMD EPYC 9554P CPU
    string(APPEND CFLAGS " -tp=zen4")
    string(APPEND CXXFLAGS " -tp=zen4")
    string(APPEND FFLAGS " -tp=zen4 -Mstack_arrays -Mallocatable=03")
    string(APPEND LDFLAGS " -tp=zen4 -Mnofma")
  elseif(GPU_TYPE STREQUAL a100) # AMD EPYC Milan 7763 CPU 
    string(APPEND CFLAGS " -tp=zen3")
    string(APPEND CXXFLAGS " -tp=zen3")
    string(APPEND FFLAGS " -tp=zen3 -Mstack_arrays -Mallocatable=03")
    string(APPEND LDFLAGS " -tp=zen3 -Mnofma")
  else()
    string(APPEND CFLAGS " -tp=cascadelake")
    string(APPEND CXXFLAGS " -tp=cascadelake")
    string(APPEND FFLAGS " -tp=cascadelake -Mstack_arrays -Mallocatable=03")
    string(APPEND LDFLAGS " -tp=cascadelake -Mnofma")
  endif()
endif()
string(APPEND SLIBS " -llapack -lblas")
if (MPILIB STREQUAL mpi-serial)
  string(APPEND SLIBS " -ldl")
endif()
string(APPEND SLIBS " -L${NETCDF_PATH}/lib -lnetcdf -lnetcdff")
message("GPU_TYPE is ${GPU_TYPE}")
message("OPENACC_GPU_OFFLOAD is ${OPENACC_GPU_OFFLOAD}")
message("OPENMP_GPU_OFFLOAD is ${OPENMP_GPU_OFFLOAD}")

if (USE_KOKKOS)
  # Generic setting that are used regardless of Architecture or Kokkos backend
  string(APPEND KOKKOS_OPTIONS " -DKokkos_ENABLE_DEPRECATED_CODE=OFF -DKokkos_ENABLE_EXPLICIT_INSTANTIATION=OFF")
  if (KOKKOS_GPU_OFFLOAD)
    string(APPEND CPPDEFS " -DGPU -DTHRUST_IGNORE_CUB_VERSION_CHECK -DHOMMEXX_ENABLE_GPU")
    string(APPEND KOKKOS_OPTIONS " -DKokkos_ENABLE_SERIAL=ON -DKokkos_ENABLE_OPENMP=OFF -DKokkos_ENABLE_AGGRESSIVE_VECTORIZATION=OFF")
    if (GPU_TYPE STREQUAL v100)
      string(APPEND KOKKOS_OPTIONS " -DKOKKOS_ARCH_VOLTA70=ON -DKokkos_ENABLE_CUDA=ON -DKokkos_ENABLE_CUDA_LAMBDA=ON -DKokkos_ENABLE_IMPL_CUDA_MALLOC_ASYNC=OFF")
      string(APPEND CXXFLAGS " -extended-lambda -Wext-lambda-captures-this -std=c++17 -arch=sm_70")
    elseif(GPU_TYPE STREQUAL a100)
      string(APPEND KOKKOS_OPTIONS " -DKokkos_ARCH_AMPERE80=ON -DKokkos_ENABLE_CUDA=ON -DKokkos_ENABLE_CUDA_LAMBDA=ON -DKokkos_ENABLE_IMPL_CUDA_MALLOC_ASYNC=OFF")
      string(APPEND CXXFLAGS " -extended-lambda -Wext-lambda-captures-this -std=c++17 -arch=sm_80")
    elseif(GPU_TYPE STREQUAL h100)
      string(APPEND KOKKOS_OPTIONS " -DKokkos_ARCH_HOPPER90=ON -DKokkos_ENABLE_CUDA=ON -DKokkos_ENABLE_CUDA_LAMBDA=ON -DKokkos_ENABLE_IMPL_CUDA_MALLOC_ASYNC=OFF")
      string(APPEND CXXFLAGS " -extended-lambda -Wext-lambda-captures-this -std=c++17 -arch=sm_90")
    else()
      message(FATAL_ERROR "GPU_TYPE ${GPU_TYPE} not supported")
    endif()
  else()
    string(APPEND KOKKOS_OPTIONS " -DKokkos_ARCH_ZEN4=ON -DKokkos_ENABLE_SERIAL=ON -DKokkos_ENABLE_OPENMP=OFF") # work-around for nvidia as kokkos is not passing "-mp" for threaded build
  endif()
  string(APPEND LDFLAGS " -lstdc++ -lkokkoscontainers -lkokkoscore -lkokkossimd ")
endif()
